require:
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 2.4

Metrics/ClassLength: 
  Max: 120
Metrics/MethodLength: 
  Max: 20
RSpec/ExampleLength:
  Max: 10
RSpec/NestedGroups:
  Max: 4
