name: Lint and RSpec tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rubocop:
    name: Lint with Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.10
      - name: Bundle Install
        run: |
          gem install bundler:1.17.2
          bundle install
      - name: Run Rubocop
        run: bundle exec rubocop
  ruby24test:
    name: Test Ruby 2.4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4.10
      - name: Remove Lock File
        run: rm Gemfile.lock
      - name: Bundle Install
        run: |
          gem install bundler:1.17.2
          bundle install --gemfile Gemfile.AR4
      - name: Run RSpec
        run: bundle exec rake spec
  ruby26test:
    name: Test Ruby 2.6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.10
      - name: Bundle Install
        run: |
          gem install bundler:1.17.2
          bundle install
      - name: Run RSpec
        run: bundle exec rake spec
  ruby31test:
    name: Test Ruby 3.1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      - name: Remove Lock File
        run: rm Gemfile.lock
      - name: Bundle Install
        run: |
          gem install bundler
          bundle install --gemfile Gemfile.AR7
        env:
          FORCED_BUNDLER_VERSION: 2.3.21
      - name: Run RSpec
        run: bundle exec rake spec
        env:
          FORCED_BUNDLER_VERSION: 2.3.21
